### ISSUE TITLE
Support for float

### ISSUE THREAD

**Issue by sajith74** [jtpereyda/boofuzz#289]
Add support for s_float.

**Comment by lucca-ruhland** [comment]
Hi, while using boofuzz I have run into the same problem and created an extension for float and integer values.
You can check it out here: https://github.com/lucca-ruhland/boofuzz-numbers.
Since I think hardly anybody will find my repository, would it be possible to contribute my code to boofuzz?
If any changes needs to be done, so that the new primitives (s_float and s_int) are more in line with this project, i would gladly rework my code.

**Comment by SR4ven** [comment]
Sure, every contribution is welcome! Feel free to open a pull request and we will review the code.
