### ISSUE TITLE
Stop Rendering All Mutations Upfront (Memory Errors when using python3)

### ISSUE THREAD

**Issue by driechersRC** [jtpereyda/boofuzz#303]
When running with python3 I seem to run out of memory easily. I have over 1 Gig of free memory and I get this error when I try to send a message just over 2Mb long. Is there anything that can be done to reduce the footprint in the python3 compatibility code? I'm sure it is not the most efficient in python2 either but I only run into the crash with python3.

```
  File "../boofuzz/boofuzz/sessions.py", line 590, in fuzz
    self._main_fuzz_loop(self._iterate_protocol())
  File "../boofuzz/boofuzz/sessions.py", line 695, in _main_fuzz_loop
    self._fuzz_current_case(*fuzz_args)
  File "../boofuzz/boofuzz/sessions.py", line 1424, in _fuzz_current_case
    self.transmit_fuzz(target, self.fuzz_node, path[-1], callback_data=callback_data)
  File "../boofuzz/boofuzz/sessions.py", line 1103, in transmit_fuzz
    data = node.render()
  File "../boofuzz/boofuzz/blocks/request.py", line 154, in render
    self._rendered += item.render()
  File "../boofuzz/boofuzz/blocks/block.py", line 231, in render
    self._rendered += item.render()
  File "../boofuzz/boofuzz/primitives/base_primitive.py", line 72, in render
    value = self._render(self._value)
  File "../boofuzz/boofuzz/primitives/string.py", line 322, in _render
    value = helpers.str_to_bytes(value)
  File "../boofuzz/boofuzz/helpers.py", line 466, in str_to_bytes
    result = six.binary_type().join(temp)
MemoryError
```

**Comment by SR4ven** [comment]
See #259

Are you using subprocesses (popen or similar)? Because the problem with that is, that it forks the main process and only reduces the memory usage afterwards.
So boofuzz with a callback containing any kind of subprocess call will need twice as much memory as without.

I guess memory optimisations would be a great benefit for boofuzz as it could then be used on weaker hardware too.
After taking a brief look at the data generation code, I think it's safe to say that there is quite some potential to save memory. All test data is generated during initialisation and not freed until the script exits.
As the data generation takes close to no time, it should be possible to generate the data for each test case individually on the go and free it right afterwards. This would reduce the memory footprint to a minimum.

**Comment by jtpereyda** [comment]
Thank you for opening @driechersRC . @SR4ven agreed, this would probably make the biggest difference. Not sure if a Python memory profiler would help with any specifics. It may be that only a few primitives need to be changed. The String and Binary types come to mind as generating all their test cases upfront.

**Comment by driechersRC** [comment]
@SR4ven I do not launch another process in any part of my code.

**Comment by SR4ven** [comment]
Sorry for the long delay @driechersRC.

Could you post a script that we can use to reproduce this issue?

**Comment by angelaren** [comment]
Hi,

I also encounter the same issue when I generate different length of bit data based on the `data_type`. The longest length data I have is 128-bit long. The issue happens when initialize the fuzzed_library for each bit_field. I'm running in pycharm and use python2.7. I have increased heap memory to 16GB but it doesn't solve the problem.

Here is a piece of my running codes:
```
 bit_data_8 = [hex(0x28), hex(0x08), hex(0x18), hex(0x30)]
 bit_data_16 = [hex(0x29), hex(0x09), hex(0x19), hex(0x31), hex(0x38), hex(0xe8), hex(0xe9)]
 bit_data_24 = [hex(0x2a), hex(0x0a), hex(0x1a)]
 bit_data_32 = [hex(0x2b), hex(0x0b), hex(0x1b), hex(0x39), hex(0xe0), hex(0xe1), hex(0xe2), hex(0xea)]
 
 with s_block("data_value_1", dep=data_type, dep_values=bit_data_8):
     s_bit_field(0, width=8 * 1, full_range=True)
 with s_block("data_value_2", dep=data_type, dep_values=bit_data_16):
     s_bit_field(0, width=8 * 2, full_range=True)
 with s_block("data_value_3", dep=data_type, dep_values=bit_data_24):
     s_bit_field(0, width=8 * 3, full_range=True)
 with s_block("data_value_4", dep=data_type, dep_values=bit_data_32):
     s_bit_field(0, width=8 * 4, full_range=True)
 ....
```
This piece of code is in the middle of the whole codes. The MemoryError happens on the 4th `s_bit_field`. If I don't initialize data based on the data type value, everything works fine. But based on the testing protocol definition, I should do such stuff. So I'm wondering when will this issued be solved....

**Comment by SR4ven** [comment]
I'm still unable to reproduce this error on my Ubuntu 19.10 VM with Python 2.7/3.7 64bit.
Boofuzz will try to render all primitives until the system runs out of memory, hence the memory error. For some reason I don't see the python exception `MemoryError`, the OS just kills the process instead.

Anyhow, this is the expected behaviour and not a bug.
`s_bit_field(0, width=8 * 4, full_range=True)` alone represents a 32bit integer with over 4 billion values which would take insanely long to fuzz with the full_range option enabled.
Apart from that, boofuzz doesn't really handle its value library efficiently, but optimising isn't trivial and time intensive. As said before, it would be much more lightweight to render the primitives on the go and discard old values. That would reduce the memory footprint to a minimum.

As for your case, are you using a 32bit version of Python? Which OS are you testing on?
Regarding the code snippet you provided: the `dep` argument of `s_block` takes the name of a primitive that it depends on. `data_type` is not defined in the piece of code shown here so your protocol definition might still be correct; I just wanted to let you know about this.

**Comment by angelaren** [comment]
@SR4ven I'm using 64-bit version of Python and running on Windows. Yes, `data_type` is a list of possible values that defined by the protocol. There are total 48 data types that will be rendered as bit_field. I've include more codes in the previous comment. In my real codes, I use many `s_bit_field()` to initialize longer message fields. I think that could be the reason why I got memory error. I'll disable `full_range` to save memory and time. Thank you for identification.

**Comment by SR4ven** [comment]
The memory error might be related to Windows then. I'll test this when I get the chance.

**Comment by jtpereyda** [comment]
@SR4ven does the title describe the primary issue?

**Comment by SR4ven** [comment]
Yes, that sums up the main issue.
