### ISSUE TITLE
Docs: Stable version

### ISSUE THREAD

**Issue by mistressofjellyfish** [jtpereyda/boofuzz#365]
Since my recent pull request was merged, the documentation on the Socket classes is now also up to date with what is the master branch on github. Unfortunately, this now documents stuff that is not available in pypy right now. AFAICT there is no way to go back in time to a doc version that matches what is currently the released version; readthedocs only gives me "latest" and some other, meaningless versions to choose from.

According to [the readthedocs docs](https://docs.readthedocs.io/en/stable/versions.html) there should be a way to automatically create a "stable" version by adding a tag "stable" to a commit. I am not too sure how it works with the tagged releases; but maybe RTD gets confused because all tags have a v in front of the semver version.

In any case, it'd be cool to set this up to avoid confusion.

**Comment by SR4ven** [comment]
I wrote to @jtpereyda about this problem a while ago. 

The reason for this is indeed the leading "v" in front of our release tags, which is not fully compliant with [semantic versioning](https://semver.org/#is-v123-a-semantic-version).

According to the docs, a branch called stable with all commits but the latest should fix the problem for now. But then again we run into another problem because the root url will direct the user to the latest tag instead of stable ([docs](https://docs.readthedocs.io/en/stable/versions.html#redirects-on-root-urls)). This can be changed by the maintainers of the RTD project, but I'm not one and I haven't heard of @jtpereyda in a while.

For future releases I'll simply create the release tags without the "v".

**Comment by SR4ven** [comment]
After getting access to the RTD project, I could create a version `stable` pointing at the stable branch (thanks to @jtpereyda for the quick reply). With the changes from #366, this issue would be hotfixed for now.

However, with the current solution, we'd have to update the stable branch whenever a new release is created. Not very convenient.
I noticed that the leading "v" in the tags doesn't seem to be an issue for RTD so the stable tag would be automatically updated on new releases. The only problem with that is, that we are currently on version `v0.1.6`, while the very first tag is `v1.0`. As 1.0 is obviously bigger than 0.1.6, the stable version of RTD would point [here](https://github.com/jtpereyda/boofuzz/tree/v1.0).

The version of this very first tag doesn't make any sense and should either be renamed or removed, which would fix our problems.
Both option should be possible, while deleting seems to be a bit simpler.
https://stackoverflow.com/questions/5480258/how-to-delete-a-remote-tag
https://stackoverflow.com/questions/1028649/how-do-you-rename-a-git-tag

Any thoughts or concerns?

**Comment by mistressofjellyfish** [comment]
I'd remove the non-sensical tag entirely. It seems to be a leftover of the sulley repository: https://github.com/OpenRCE/sulley/tree/v1.0

**Comment by SR4ven** [comment]
Tag is deleted and everything works as expected.
