### ISSUE TITLE
Monitors: procmon, netmon, vmcontrol

### ISSUE THREAD

**Issue by mistressofjellyfish** [jtpereyda/boofuzz#380]
So, currently, there are three nearly identical monitor interfaces: procmon, netmon and vmcontrol, with a huge degree of inconsitency. I've now stared at those for more than an hour and still can't find out what the difference between a procmon and a netmon is, besides that those apparently have different options - maybe, because that depends on the concrete implementation - and that procmons must have an "crash_filename" attribute.

So, to spare myself some future trouble I'd like to go at it with an axe and propose the following:

- procmon, netmon and vmcontrol all will be standardized into one interface, `TargetMonitor`.
- Instead of separate arguments, the target accepts a list of Classes implementing `TargetMonitor`, to which items can be appended later.
- Monitors will be called at the same place they are now, in the order that they appear in the list.
- Obviously, methods that aren't of a particular interest to a specific monitor simply ignore those calls.

Specifically, this also solves my headache whether the class `External` from `boofuzz/instrumentation.py` is now a network- or a process monitor, or neither of them, or both.

What are your thoughts on this?

**Comment by SR4ven** [comment]
I'd appreciate a rework of the monitor interfaces.

As far as I know, the procmon is used for monitoring/restarting the process on the target device.
The netmon seems to be a service to capture network packets using pcapy. I've never used it though.
@jtpereyda is likely more into those monitors.

Your approach seems reasonable, feel free to open a PR!

**Comment by jtpereyda** [comment]
@mistressofjellyfish  Clean up would be great. Your summary sounds reasonable at first glance. @SR4ven 's description is accurate. Procmon monitors the process, netmon collects packets and associates them with each test case. The VM monitor is supposed to start and stop and revert/restart VMs. For some targets, using a VM can get you a lot more consistency of initial state. I've never used it myself.

**Comment by jtpereyda** [comment]
Haven't reviewed the PR yet.

@SR4ven regarding release cadence, I'm inclined to merge it in now and note the breaking changes in the release notes. That's what v0 sequences are for. Branching creates overhead, and forces us to wait until we feel ready to commit to a v1 before releasing. It also creates a divergent user base, and keeps some features available in some branches and some in others. I think there are a few breaking changes in store for major feature upgrades.

That said, we should try to minimize the breakage as much as possible. I prefer adding a small shim here and there to avoid breakage, rather than branching out. However, if this change requires too much shim code to keep compatible, we can break compatibility.

If existing code does need to change, let's aim to keep the new code at least somewhat conceptually similar. E.g., maybe there is a new common interface, but the procmon/netmon class names stay the same. Maybe we keep old argument names that could be slightly improved, or create aliases to help.

Often times backwards compatibility is not as impossible as it first seems. There is some code overhead, but that might be worth it if we can save a lot of users a lot of pain. If you've messed with py2/py3 compatibility, you've probably noticed that a lot of the breaking changes could have been fixed with a few aliases.

**Comment by SR4ven** [comment]
That sounds reasonable.
Thanks for your input @jtpereyda!

So shall we include these changes in v0.2.0 or in a later release?
Also, what about deprecating py2? Is that something we want to work on on a separate branch first? And would that be worth a major release version?

**Comment by mistressofjellyfish** [comment]
On breaking changes: The only real breaking change in my PR as of now is the netmon_options and procmon_options parameters to the session object. These fundamentally can't be used without guessing on the list of monitors passed - imagine, for example, multiple network monitors, to which should the passed options apply?

My current solution to this are callbacks that are fired once a Monitor becomes alive. Not excellent, and I plan to move the option setting stuff into the respective monitor (so basically it's the same behavior, just a different place where the dict gets added). Currently the set_options-Method on these classes provide more or less the same experience by calling `set_options(**mon_options)`. However I sill think that this can be improved, so feel free to propose a better solution :)

**Comment by jtpereyda** [comment]
@SR4ven Yes to v0.2 -- minor version bump to signal more significant changes. Re Python 2 compatibility, see here https://github.com/jtpereyda/boofuzz/issues/370 -- I don't think we should break it until we have an update or replacement for pydbg, or decide to isolate pydbg as a Python 2 utility.

@mistressofjellyfish Hope to check out the code soon.
