### ISSUE TITLE
total_num_mutations wrong with s_bytes?

### ISSUE THREAD

**Issue by kuraraneko** [jtpereyda/boofuzz#400]
when assign the size for s_bytes, total_num_mutations is not correct?

a simple test:

```py
from boofuzz import *


def main():
    session = Session(
        target=Target(
            connection=TCPSocketConnection("127.0.0.1", 80)
        ),
    )

    s_initialize(name="Test")
    s_bytes("\x00\x00",size=2)
    session.connect(s_get("Test"))
    session.fuzz()

if __name__ == "__main__":
    main()
```

The output:
```
[2020-02-28 14:28:32,169] Test Case: 21: Test.no-name.21
[2020-02-28 14:28:32,169]     Info: Type: Bytes. Default value: '\x00\x00'. Case 21 of 65 overall.
[2020-02-28 14:28:32,169]     Info: Opening target connection (127.0.0.1:80)...
[2020-02-28 14:28:32,169]     Info: Connection opened.
[2020-02-28 14:28:32,169]   Test Step: Fuzzing Node 'Test'
[2020-02-28 14:28:32,169]     Info: Sending 2 bytes...
[2020-02-28 14:28:32,169]     Transmitted 2 bytes: ff ff '\xff\xff'
[2020-02-28 14:28:32,170]     Info: Closing target connection...
[2020-02-28 14:28:32,170]     Info: Connection closed.

Fuzzing session completed. Keeping webinterface up on localhost:26000 
Press ENTER to close webinterface

```

The total_num_mutations is 65, but boofuzz finish fuzz at case 21.

Is this a bug?

**Comment by SR4ven** [comment]
Thanks for reporting this bug @kuraraneko!

I'm working on a fix and linked the PR.
It would be very nice if you could test the fix and verify that everything works as intended.

**Comment by keisentraut** [comment]
The bug is in my code in the function `num_mutations` in the `boofuzz/primitives/bytes.py` file introduced by #302. The calculation of the number of mutations is quite difficult, because the fuzzing strategy for an arbitrary length, binary string is:

- replace binary value with list of static binary strings
- replace each 1 byte block in original value with list of static 1byte strings
- replace each 2 byte block in original value with list of static 2byte strings
- replace each 4 byte block in original value with list of static 4byte strings

However, if you set a `size` field, it will skip the test cases longer than two bytes from the first bullet point. The  `num_mutations` did not account for this. As a workaround, do not set a `size` field, then you will have some more (maybe useless) testcases, but the number is correct.

To be honest, it is hard to come up with a formula which calculates the number of testcases for all circumstances. Of course, `num_mutations` could generate all testcases and simply count them, but this is very inefficient. I would need to think about this, but it seems that @SR4ven is already on fixing it.

**Comment by jtpereyda** [comment]
> However, if you set a size field, it will skip the test cases longer than two bytes from the first bullet point.

I wonder why this is.

**Comment by keisentraut** [comment]
> I wonder why this is.

see https://github.com/jtpereyda/boofuzz/pull/401#issuecomment-593512741. 
Short answer: If you set `size`, this primitive does not change length. If you set `maxlen`, it will truncate.

**Comment by jtpereyda** [comment]
OK, I get the size/max_len thing now.

If you specify size, the field size is fixed. Longer fuzz values are truncated. Shorter fuzz values are padded.

If you specify max_len (but not size): Longer fuzz values are truncated. Shorter fuzz values are not padded.

If you specify neither: All fuzz values go through as-is.
