### ISSUE TITLE
Multiple cases from a single node?

### ISSUE THREAD

**Issue by MarkFuller1** [jtpereyda/boofuzz#473]
Ive written a small program to test a DNS server, however the single test case(one node) that I've written has 2464 cases? I do not have any calls to s_repeat so I dont know what is causing this. How do I change this?

```python
from boofuzz import *


def encode_domain(name: str) -> int:
    tokens = name.split(".")

    res = []

    for token in tokens:
        token_len = len(token)
        res.append(token_len)

        for c in token:
            res.append(ord(c))

    return res


def create_header(name="query", id=0, flags=0, qcount=0, ancount=0, nscount=0, arcount=0):
    s_initialize(name)
    s_short(id, name="TransactionID")
    s_short(flags, name="Flags")
    s_short(qcount, name="Questions", endian=">")
    s_short(ancount, name="Answer", endian=">")
    s_short(nscount, name="NameServer", endian=">")
    s_short(arcount, name="Additional", endian=">")


def create_question(q_name, name="query", q_type=0xff, q_class=0x1):
    s_switch(name)
    if s_block_start("question"):
        for b in encode_domain(q_name):
            s_byte(b)
        s_short(q_type, endian=">")
        s_short(q_class, endian=">")
    s_block_end("question")


def addRR(dname, type, classn, ttl, rdlength, rdata, name='query'):
    s_switch(name)
    s_string(dname)
    s_short(type)
    s_short(classn)
    s_long(ttl)
    s_short(rdlength)
    s_string(rdata)


create_header(id=1, qcount=1)
create_question(q_name="google.com.")

sess = Session(
    target=Target(
        connection=UDPSocketConnection("192.168.254.38", 12345)),
    restart_interval=0,
    restart_threshold=0)

sess.connect(fb.s_get("query"))

sess.fuzz()
```

**Comment by cq674350529** [comment]
It's expected behaviour. In your simple example, many `s_xxx()` are used. Each of them represents a primitive, and will be mutated in default. Take `s_byte()` as an example, range of a byte is 0~255. when mutating this single primitive, it will generate some tests such as 0, 8,15,31,63,85,127 for this single primitive (maybe not precise).  As to your example, since there are many primitives and each primitive will be mutated, so many cases will be generated. And this is what fuzzing actually does.

If you want to reduce the generated test cases, you can choose to only fuzz some selected fields. There is an attribute `fuzzable` available in `s_xxx()`, if set to `False`, the corresponding primitive won't be mutated, e.g. `s_short(id, name="TransactionID", fuzzable=False)`
