### ISSUE TITLE
arguments discrepance between s_string() and String()

### ISSUE THREAD

**Issue by cq674350529** [jtpereyda/boofuzz#590]
It's possible to extend the fuzz libary via option `fuzz_values`. However, there is an argument discrepance bwtween `String()` and `s_string()`.

It's ok when using `String()`.

```
hello = Request("hello", children=(
        String("name", "boofuzz", max_len=0, fuzz_values=["boofuzz123","boofuzzaaa"])
    ))
```

However, these is no option `fuzz_values` when using `s_string()`, according to its definition:

https://github.com/jtpereyda/boofuzz/blob/e371ce178705f1ab90e1c824397ec36e90e083a7/boofuzz/__init__.py#L737

Since `s_string()` is the old school Spike-style static protocol definition format, does it mean that using the former is preferable?

**Comment by SR4ven** [comment]
Good point @cq674350529.
The reason for this discrepancy in the args of the old and new format is that the static format s_* primitives don't take kwargs.
`fuzz_values` comes from `Fuzzable` which all primitives inherit from so it's not just a thing for `String()`.

I'd say the new format is definitely preferable and it would make the API and code more clean if we'd remove the old static format. I think we've discussed this somewhere with @jtpereyda and it was found that backward compatibility is more important.
Maybe we could mark s_* blocks and primitives deprecated so that new users don't get tempted to use them?

In case we want to keep supporting s_* primitives, we could add *args and **kwargs. That should at least fix this specific issue.

**Comment by cq674350529** [comment]
> The reason for this discrepancy in the args of the old and new format is that the static format s_* primitives don't take kwargs. `fuzz_values` comes from `Fuzzable` which all primitives inherit from so it's not just a thing for `String()`.

Yes, that's the point. And as you mentioned, adding `*args` and `**kwargs` can resolve this. I'm just curious about this behaviour, and there might be some reasons behind it. Thanks for your detailed explanation. @SR4ven 

One more thing, if using the former, one **must** specify name to each primitive manually, even if the name is empty or useless. Is it possible to change it into the `Spike-style` way?
```
hello = Request("hello", children=(
    String("boofuzz", name="mark", max_len=0, fuzz_values=["boofuzz123","boofuzzaaa"])
))
```

**Comment by SR4ven** [comment]
There's no need to set a name with the new format.
You can do something like this, which will generate the default name `String1`
```python
String(default_value="boofuzz", max_len=0, fuzz_values=["boofuzz123", "boofuzzaaa"])
```

**Comment by cq674350529** [comment]
Yeah, actually I prefer the following:
```python
String("boofuzz", max_len=0, fuzz_values=["boofuzz123", "boofuzzaaa"])
```

When defining many primitives, less means faster and convenience, just my original opinion :)

**Comment by SR4ven** [comment]
I think at some point we agreed to place the name argument first because every primitive and block has a name but not everyone has a default value. Not exactly sure though.
However, now it's too late to change the order. It would be a breaking change which we're trying to avoid.

**Comment by cq674350529** [comment]
Indeed a breaking change. Neverthelsess, it doesn't matter, maybe just my personal favor.

Thanks!
